### ISSUE TITLE
Reduce or remove errors and warnings when parsing invalid UTF-8

### ISSUE THREAD

**Issue by bquorning** [dgollahon/rspectre#17]
When running against this bit of code:
```rb
RSpec.describe "invalid UTF8" do
  let(:invalid_utf8) { "hello \255" }

  it "is not the answer" do
    expect(invalid_utf8).to_not eq(42)
  end
end
```
I get these errors and warnings:
```
utf8_spec.rb:4:24: error: literal contains escape sequences incompatible with UTF-8
utf8_spec.rb:4:   let(:invalid_utf8) { "hello \255" }
utf8_spec.rb:4:                        ^~~~~~~~~~~~
Warning! Skipping utf8_spec.rb due to parsing error!
utf8_spec.rb:4:24: error: literal contains escape sequences incompatible with UTF-8
utf8_spec.rb:4:   let(:invalid_utf8) { "hello \255" }
utf8_spec.rb:4:                        ^~~~~~~~~~~~
Unable to resolve `let` on line 4.
```

**Comment by dgollahon** [comment]
@bquorning:  Yeah, `parser` doesn't support non-utf8 strings out of the box so right now I just skip any test files with invalid sequences. I'm pretty sure `rubocop` has a patch for this, but I haven't had a chance to extract it yet. Hopefully I can get this stuff working sometime soon. If not, I do want to at least consolidate all the warnings so it just shows one message per file.

**Comment by bquorning** [comment]
After reading https://github.com/whitequark/parser/issues/323 I don’t think there’s any hope of fixing this issue…

**Comment by dgollahon** [comment]
Actually, I don't think so. The [workaround](https://github.com/whitequark/parser/issues/323#issuecomment-253606403) ought to work just fine for RSpectre. I don't think there are any meaningful cases where I want to do operations on strings that have been parsed out with `parser` so just letting "invalid" strings fly on through should be fine for us.
