### ISSUE TITLE
Fix ruby 3.x compatibility

### ISSUE THREAD

**Issue by dgollahon** [dgollahon/rspectre#46]
I am not currently using 3.x but I suspect there may be some issues related to how various arguments get forward and may require using [ruby2_keywords](https://github.com/ruby/ruby2_keywords). This is just a reminder for me to check if this is a problem or not.

**Comment by dgollahon** [comment]
There are issues--the naive forwarding breaks in some cases. Here is an [example from `mutant`](https://github.com/mbj/mutant/commit/d146f957a9316c826c6e846c24ae82a698648a32#diff-68198e1d68f5364ace6fdb3be566c8f96d56b54dc92939fbfb53ad242ca533a1R3-R19). This applies to at least shared_examples, but maybe niche uses of other constructs as well. The forwarding should work properly in each version of ruby so I either need to figure out how to get `ruby2_keywords` to work (the naive thing I tried did not work) or just switch on if 2.7.x is running and forward `*args, &blk` v.s. `*args, **kwargs, &blk` based on that.

**Comment by bquorning** [comment]
After upgrading to Ruby 3.1/3.2 I am also running into this problem with `shared_examples` taking “block keyword arguments”. I think dropping Ruby 2.7 is a fine approach now that it’s EOL anyway.
