### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by jaynetics** [dgollahon/rspectre#51]
The relaxation of the parser dependency in https://github.com/dgollahon/rspectre/commit/018951554afccbffb34b426adb8b7e8ccf846d0f is not published yet.

**Comment by dgollahon** [comment]
Hi @jaynetics, I will try to look at open PRs and do a release shortly. I've been a bit swamped lately but should hopefully have free time tomorrow.

**Comment by dgollahon** [comment]
0.0.4 is released, thanks for the nudge @jaynetics

**Comment by jaynetics** [comment]
thanks for the release!
